### ISSUE TITLE
How can I override layout.blade.php?

### ISSUE THREAD

**Issue by blitux** [stevemo/cpanel#2]
Hi Steve, 

First of all, thank you for releasing this package to the comunity. It's a great work.

I can't override layouts.blade.php. I modified the config file with the following, but doesn't seem to work:

```
...
 'views' => array(
        'layout' => 'hello',
...
```

Thank you.

**Comment by stevemo** [comment]
the problem was only for dashboard, login and register views. It is fix in the latest develop branch.
