### ISSUE TITLE
i've an error When I create a user with php artisan cpanel:user

### ISSUE THREAD

**Issue by silverpark** [stevemo/cpanel#24]
[RuntimeException]  
  Error generating hash from string, your PHP environment is probably incompatible. Try running [vendor/ircmaxell/password-compat/version-test.php] to check compatibility or use an alternative hashing str  
  ategy.

**Comment by stevemo** [comment]
I have tried with Laravel 4.0.\* and Laravel 4.1.\* and didn't have issue. What is your setup?
