### ISSUE TITLE
AdminLTE

### ISSUE THREAD

**Issue by aaronflorey** [stevemo/cpanel#27]
Will you be bringing back the admin lte theme? It was much nicer then the one in master (no offence)

**Comment by stevemo** [comment]
The master branch is not updated. this is why you don't have Admin LTE theme. Still working on the develop branch. When it is completed the master branch will have Admin LTE theme.

**Comment by aaronflorey** [comment]
Oh. I was using the develop branch, but i couldn't override views in the config file. I might fix that up and submit a pull request.

**Comment by stevemo** [comment]
In the develop branch you do not need the config option anymore. just do php artisan view:publish stevemo\cpanel
This will copy all the cpanel views in app/views/packages/stevemo/cpanel. then you can override from there
