### ISSUE TITLE
Dependency Conflict

### ISSUE THREAD

**Issue by mikhailkozlov** [stevemo/cpanel#31]
right now:

```
php: >=5.3.0
anahkiasen/former: dev-master
```

Since last release dependency on `5.4.0` was added to Former, so now composer is really not happy about installing the package. 

Is it possible to lock into using something more permanent?

Btw, thanks a lot for the package.

**Comment by stevemo** [comment]
updated php to 5.4 and former to 3.5.*

**Comment by mikhailkozlov** [comment]
Thanks. 

That does not help me as I stuck with php 5.3 but I'm sure people will appreciate.
