### ISSUE TITLE
I can't override the view dashboard.index

### ISSUE THREAD

**Issue by jruzafa** [stevemo/cpanel#32]
I tried to configure it with artisan view: publish stevemo / cpanel and does not work, I also tried to set it by app / config / packages / stevemo / cpanel / config.php

**Comment by jorgecolonconsulting** [comment]
@jruzafa 

Should be able to with

``` bash
./artisan view:publish stevemo/cpanel
```

Then edit `app/views/packages/stevemo/cpanel/dashboard/index.blade.php`.

**Comment by jorgecolonconsulting** [comment]
Actually that applies to the develop branch. Check @stevemo's notes on issue #29.
