### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by Kreshnik** [stevemo/cpanel#37]
The package is missing the Anahkiasen/former dependency.

**Comment by jorgecolonconsulting** [comment]
+1 :+1:

**Comment by stevemo** [comment]
I am not using it anymore under the dev-develop branch. You can always pull it in your own composer.json file if you need it!.

**Comment by jorgecolonconsulting** [comment]
Oh I see what's wrong. Your README says to use dev-develop, that's probably what caused the confusion. Just needs an update. @stevemo

**Comment by stevemo** [comment]
I see. I will update the readme. Thanks

**Comment by jorgecolonconsulting** [comment]
You're welcome. :)
