### ISSUE TITLE
Is there any way to integrate other models to the admin

### ISSUE THREAD

**Issue by prabhakaran8737** [stevemo/cpanel#45]
I am trying to integrate the basic CRUD of all the models or specific models into the admin. But I could not see any options like that. When I dig up the code there are no dynamic routes. Any solution to solve this situation?

**Comment by stevemo** [comment]
Hi there this is what I do when i need extra route in the admin.
1- Create a Controller that extend Stevemo\Cpanel\Controllers\BaseController
2- Create routes in your route.php like any other route for your app. ex: 
`Route::get('my-new-route', array(
        'as'     => 'myNewRoute',
        'uses'   => 'MyController@index',
        'before' => 'auth.cpanel:some-permission'
    ));
`
3- create your view.

You should be good to go.

If you need more help drop me a email at steve@stevemo.ca

Cheers

**Comment by prabhakaran8737** [comment]
Okay clear me one. I have decided to bind you login to my package, so when I install my packaged yours will also be added. Is there any efficient way to do this?
