### ISSUE TITLE
Getting started using Cpanel to protect other routes

### ISSUE THREAD

**Issue by gwilymgj** [stevemo/cpanel#9]
Hi,

So to protect a route is nice and easy, something like this in routes.php passes a route through Cpanel:

```
Route::group(array('before' => 'auth.cpanel'), function() {
    Route::resource('admin/project', 'App\Controllers\ProjectController');
});
```

However this does not work, it returns an 'Undefined offset: 2' - any ideas why?:

```
Route::group(array('before' => 'auth.cpanel'), function() {
    Route::get('admin/project', array('as' => 'project.index', 'uses' => 'App\Controllers\ProjectController@index'));
});
```

**Comment by stevemo** [comment]
Sorry for the delay.... the auth.cpanel filter accept argument for not standard resource route. By default the filter expect a name route. So in your case 
Route::group(array('before' => 'auth.cpanel:project.index'), function() {
    Route::get('admin/project', array('as' => 'project.index', 'uses' => 'App\Controllers\ProjectController@index'));
});
